using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json;

namespace DelveMapOverlay;

/// <summary>
/// Reference data for delve nodes (from nodes.json, generated by build_backbone.ps1)
/// plus the reward/tier derivation system keyed on the game's feature Ids.
/// </summary>
public static class NodeBackbone
{
    public sealed class NodeInfo
    {
        public List<string> Biome { get; set; } = new List<string>();
        public List<string> Contents { get; set; } = new List<string>();
        public int? TierMin { get; set; }
        public int? TierMax { get; set; }
        public int? MinDepth { get; set; }
        public string Portal { get; set; }
        public string Boss { get; set; }
    }

    public static string Path { get; private set; } = @"F:\PoE\PoE-DEV\DelveMap\nodes.json";
    public static IReadOnlyDictionary<string, NodeInfo> Nodes { get; private set; } =
        new Dictionary<string, NodeInfo>();
    public static bool Loaded { get; private set; }

    /// <summary>
    /// Looks for nodes.json next to the plugin DLL (directory this assembly lives in),
    /// falling back to the canonical dev path if the shipped copy is missing.
    /// </summary>
    public static bool Load(string pluginDir = null)
    {
        var candidates = new List<string>();
        if (!string.IsNullOrEmpty(pluginDir))
            candidates.Add(System.IO.Path.Combine(pluginDir, "nodes.json"));
        candidates.Add(Path);

        foreach (var candidate in candidates)
        {
            if (!File.Exists(candidate)) continue;
            try
            {
                var json = File.ReadAllText(candidate);
                var dict = JsonConvert.DeserializeObject<Dictionary<string, NodeInfo>>(json);
                if (dict == null || dict.Count == 0) continue;

                Path = candidate;
                Nodes = dict;
                Loaded = true;
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"DelveMapOverlay backbone load failed ({candidate}): {ex.Message}");
            }
        }

        return false;
    }

    public static bool TryGet(string name, out NodeInfo info)
    {
        return Nodes.TryGetValue(name ?? "", out info);
    }

    // -------------------------------------------------------------------------------
    // Reward derivation from feature Ids. DelveFeatures entries share a display Name
    // across several feature Ids, and the Id suffix encodes the exact reward variant
    // (e.g. MineSkeletonArmour vs MineSkeletonCurrency vs MineSkeletonGems). The reward
    // is always derived from the live per-cell feature Id, never the static name.
    // -------------------------------------------------------------------------------

    /// <summary>
    /// Maps a feature Id to its reward label. Priority order matters:
    /// exact/encounter ids first, then suffix matching (most specific first).
    /// Unknown ids -> "" (no reward).
    /// </summary>
    public static string RewardOfId(string id)
    {
        if (string.IsNullOrEmpty(id)) return "";

        switch (id)
        {
            case "Legion": return "Legion";
            case "Breach": return "Breach";
            case "Beyond": return "Beyond";
            case "Harbinger": return "Harbinger";
            case "Strongbox": return "Strongboxes";
            case "DarkChest": return "Strongboxes";
            case "Nothing": return "";
        }

        if (id.StartsWith("Azurite", StringComparison.OrdinalIgnoreCase)) return "Azurite";

        if (id.EndsWith("Fossil", StringComparison.OrdinalIgnoreCase)) return "Fossils";
        if (id.EndsWith("Minions", StringComparison.OrdinalIgnoreCase)) return "Minion/Aura";
        if (id.EndsWith("Talisman", StringComparison.OrdinalIgnoreCase)) return "Talismans";
        if (id.Contains("Essence", StringComparison.OrdinalIgnoreCase)) return "Essences";
        if (id.Contains("Bestiary", StringComparison.OrdinalIgnoreCase)) return "Bestiary";
        if (id.EndsWith("Abyss", StringComparison.OrdinalIgnoreCase)) return "Abyss";
        if (id.EndsWith("Chaos", StringComparison.OrdinalIgnoreCase)) return "Chaos";
        if (id.EndsWith("Curse", StringComparison.OrdinalIgnoreCase)) return "Mana/Curse";
        if (id.EndsWith("Animalistic", StringComparison.OrdinalIgnoreCase)) return "Animalistic";
        if (id.EndsWith("Physical", StringComparison.OrdinalIgnoreCase)) return "Physical";
        if (id.EndsWith("Fire", StringComparison.OrdinalIgnoreCase)) return "Fire";
        if (id.EndsWith("Cold", StringComparison.OrdinalIgnoreCase)) return "Cold";
        if (id.EndsWith("Lightning", StringComparison.OrdinalIgnoreCase)) return "Lightning";

        // Warband ids embed the element mid-string (e.g. SulphurLightningWarbands1).
        if (id.Contains("Warbands", StringComparison.OrdinalIgnoreCase))
        {
            if (id.Contains("Fire", StringComparison.OrdinalIgnoreCase)) return "Fire";
            if (id.Contains("Cold", StringComparison.OrdinalIgnoreCase)) return "Cold";
            if (id.Contains("Lightning", StringComparison.OrdinalIgnoreCase)) return "Lightning";
        }

        if (id.EndsWith("Armour", StringComparison.OrdinalIgnoreCase)) return "Armour";
        if (id.EndsWith("Weapon", StringComparison.OrdinalIgnoreCase) ||
            id.EndsWith("Weapons", StringComparison.OrdinalIgnoreCase)) return "Weapons";
        if (id.EndsWith("Gems", StringComparison.OrdinalIgnoreCase)) return "Gems";
        if (id.EndsWith("Currency", StringComparison.OrdinalIgnoreCase)) return "Currency";
        if (id.EndsWith("Trinkets", StringComparison.OrdinalIgnoreCase) ||
            id.EndsWith("Tinkets", StringComparison.OrdinalIgnoreCase)) return "Jewellery";
        if (id.EndsWith("Maps", StringComparison.OrdinalIgnoreCase)) return "Maps";
        if (id.EndsWith("ChamberTier", StringComparison.OrdinalIgnoreCase)) return "Chamber";
        if (id.EndsWith("Boss", StringComparison.OrdinalIgnoreCase)) return "Boss";
        if (id.StartsWith("Obstruction", StringComparison.OrdinalIgnoreCase)) return "Hidden Path";
        if (id.EndsWith("Generic", StringComparison.OrdinalIgnoreCase)) return "Loot";
        return "";
    }

    /// <summary>
    /// Tier of a feature Id, 0 = no tier. Only two families carry real tiers in the
    /// game data: Azurite (Azurite1_* = T1 Cavity, Azurite2_* = T2 Vault, Azurite3_* =
    /// T3 Fissure) and Chambers (*ChamberTier0..4). Everything else is tier-uniform.
    /// </summary>
    public static int TierOfId(string id)
    {
        if (string.IsNullOrEmpty(id)) return 0;

        if (id.StartsWith("Azurite", StringComparison.OrdinalIgnoreCase) && id.Length > 7)
        {
            var d = id[7];
            if (d >= '1' && d <= '3') return d - '0';
            return 0;
        }

        var idx = id.IndexOf("ChamberTier", StringComparison.OrdinalIgnoreCase);
        if (idx >= 0)
        {
            var p = idx + "ChamberTier".Length;
            if (p < id.Length && id[p] >= '0' && id[p] <= '4') return id[p] - '0';
            return 0;
        }

        return 0;
    }

    // -------------------------------------------------------------------------------
    // Reward tables, built from the live DelveFeatures table (reward -> node names,
    // reward -> tiers, and the sorted list of all rewards for the filter UI).
    // -------------------------------------------------------------------------------

    public static IReadOnlyList<string> AllRewards { get; private set; } = new List<string>();
    public static IReadOnlyDictionary<string, IReadOnlyList<string>> RewardNodes { get; private set; } =
        new Dictionary<string, IReadOnlyList<string>>();
    public static IReadOnlyDictionary<string, IReadOnlyList<int>> RewardTiers { get; private set; } =
        new Dictionary<string, IReadOnlyList<int>>();

    public static void BuildRewardData(IEnumerable<dynamic> features)
    {
        var nodesByReward = new Dictionary<string, SortedSet<string>>(StringComparer.OrdinalIgnoreCase);
        var tiersByReward = new Dictionary<string, SortedSet<int>>(StringComparer.OrdinalIgnoreCase);

        foreach (var f in features)
        {
            string name = f.Name as string ?? "";
            string id = f.Id as string ?? "";
            if (name.Length == 0) continue;

            var r = RewardOfId(id);
            if (r.Length == 0) continue;

            if (!nodesByReward.TryGetValue(r, out var ns))
                nodesByReward[r] = ns = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);
            ns.Add(name);

            var t = TierOfId(id);
            if (t > 0)
            {
                if (!tiersByReward.TryGetValue(r, out var ts))
                    tiersByReward[r] = ts = new SortedSet<int>();
                ts.Add(t);
            }
        }

        RewardNodes = nodesByReward.ToDictionary(
            kv => kv.Key,
            kv => (IReadOnlyList<string>)kv.Value.ToList(),
            StringComparer.OrdinalIgnoreCase);
        RewardTiers = tiersByReward.ToDictionary(
            kv => kv.Key,
            kv => (IReadOnlyList<int>)kv.Value.OrderBy(x => x).ToList(),
            StringComparer.OrdinalIgnoreCase);
        AllRewards = nodesByReward.Keys
            .OrderBy(k => k, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    /// <summary>
    /// Compact tier range label for a reward (e.g. Azurite -> "T1-3", Chamber -> "T1-4").
    /// Empty string when the reward has no real tiering.
    /// </summary>
    public static string RewardTierRange(string reward)
    {
        if (string.IsNullOrEmpty(reward)) return "";
        if (!RewardTiers.TryGetValue(reward, out var tiers) || tiers.Count == 0) return "";
        return $"T{tiers[0]}-{tiers[tiers.Count - 1]}";
    }

    /// <summary>
    /// Rewards that are valuable/distinctive enough to be enabled by default.
    /// Everything else defaults to disabled in the filter list.
    /// </summary>
    private static readonly HashSet<string> ChaseRewards = new(StringComparer.OrdinalIgnoreCase)
    {
        "Boss", "Chamber", "Currency", "Azurite", "Fossils", "Minion/Aura", "Chaos",
        "Animalistic", "Physical", "Talismans", "Abyss", "Mana/Curse", "Essences",
        "Cold", "Fire", "Lightning", "Maps", "Strongboxes", "Legion", "Breach",
        "Beyond", "Harbinger", "Hidden Path",
    };

    public static bool IsChaseReward(string reward)
    {
        return !string.IsNullOrEmpty(reward) && ChaseRewards.Contains(reward);
    }

    /// <summary>
    /// Default weight per reward (-10..10) used when seeding/ resetting filters.
    /// Weight drives both saturation and opacity: high = vivid + opaque, low = gray + faint.
    /// Values are based on community delve farming guides (fossils, bosses, minion/aura and
    /// mana/curse nodes are top profit; generic weapon/armour loot nodes are trash).
    /// </summary>
    private static readonly Dictionary<string, float> DefaultWeights = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Boss"] = 10f,
        ["Minion/Aura"] = 9f,
        ["Mana/Curse"] = 9f,
        ["Fossils"] = 8f,
        ["Chamber"] = 5f,
        ["Azurite"] = 5f,
        ["Currency"] = 4f,
        ["Hidden Path"] = 3f,
        ["Legion"] = 3f,
        ["Breach"] = 3f,
        ["Harbinger"] = 3f,
        ["Beyond"] = 3f,
        ["Strongboxes"] = 3f,
        ["Chaos"] = 3f,
        ["Essences"] = 2f,
        ["Talismans"] = 2f,
        ["Abyss"] = 2f,
        ["Animalistic"] = 2f,
        ["Physical"] = 2f,
        ["Fire"] = 1f,
        ["Cold"] = 1f,
        ["Lightning"] = 1f,
        ["Maps"] = 1f,
        ["Bestiary"] = 1f,
        ["Weapons"] = -2f,
        ["Armour"] = -2f,
        ["Gems"] = -2f,
        ["Jewellery"] = -2f,
        ["Loot"] = -2f,
    };

    /// <summary>
    /// Default weight for a reward label (0f when unlisted).
    /// </summary>
    public static float DefaultWeight(string reward)
    {
        if (string.IsNullOrEmpty(reward)) return 0f;
        return DefaultWeights.TryGetValue(reward, out var w) ? w : 0f;
    }

    /// <summary>
    /// Default per-tier weights for a reward that has real tiering. Azurite tiers ramp
    /// with depth value: T1 (Cavity) low, T2 (Vault) mid, T3 (Fissure) high.
    /// </summary>
    public static System.Collections.Generic.Dictionary<int, float> DefaultTierWeights(string reward)
    {
        var map = new System.Collections.Generic.Dictionary<int, float>();
        if (reward == "Azurite")
        {
            map[1] = -4f; // Cavity
            map[2] = 2f;  // Vault
            map[3] = 8f;  // Fissure
        }
        return map;
    }

    /// <summary>All tiers a reward can carry (from live feature Ids), ascending.</summary>
    public static System.Collections.Generic.List<int> AllTiersOf(string reward)
    {
        if (RewardTiers != null && RewardTiers.TryGetValue(reward, out var set))
            return set.ToList();
        return new System.Collections.Generic.List<int>();
    }

    /// <summary>
    /// Fallback reward list used to seed filters when the live feature table wasn't
    /// available at load time. All known reward labels, alphabetical.
    /// </summary>
    public static IReadOnlyList<string> DefaultRewards { get; } = new[]
    {
        "Abyss", "Animalistic", "Armour", "Azurite", "Bestiary", "Beyond", "Boss",
        "Breach", "Chamber", "Chaos", "Cold", "Currency", "Essences", "Fire", "Fossils",
        "Gems", "Harbinger", "Hidden Path", "Jewellery", "Legion", "Lightning", "Loot",
        "Mana/Curse", "Maps", "Minion/Aura", "Physical", "Strongboxes", "Talismans", "Weapons",
    };
}
